/**
 * Numerical parity check: the hand-written TypeScript forward pass must produce
 * the same numbers as PyTorch.
 *
 * Reference outputs in scripts/parity-cases.json are generated by loading the
 * exported weight blob back into the real torch modules and running them — so
 * this validates the export format and the TS implementation together.
 *
 * Usage:
 *   npx tsc src/lib/synmedix/inference.ts --outDir <tmp> --module esnext \
 *     --target es2020 --moduleResolution bundler --skipLibCheck
 *   node scripts/verify-parity.mjs <tmp>/inference.js
 */
import { readFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

const modulePath = process.argv[2]
if (!modulePath) {
  console.error('usage: node scripts/verify-parity.mjs <compiled inference.js>')
  process.exit(2)
}

const manifest = JSON.parse(readFileSync('public/models/synmedix-generator.json', 'utf8'))
const bin = readFileSync('public/models/synmedix-generator.bin')
const buffer = bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength)
const cases = JSON.parse(readFileSync('scripts/parity-cases.json', 'utf8'))

// Stub fetch so the browser-oriented loader runs unchanged under Node.
globalThis.fetch = async (url) =>
  String(url).endsWith('.json')
    ? { ok: true, json: async () => manifest }
    : { ok: true, arrayBuffer: async () => buffer }

const { SynMedixGenerator } = await import(pathToFileURL(modulePath).href)
const generator = await SynMedixGenerator.load('/models/synmedix-generator')

let worst = 0
let failures = 0

cases.forEach((testCase, i) => {
  const actual = generator.generate({
    z: testCase.z,
    ageBucket: testCase.ageBucket,
    gender: testCase.gender,
    diagnosis: testCase.diagnosis,
  })

  const diffs = actual.map((v, j) => Math.abs(v - testCase.expected[j]))
  const maxDiff = Math.max(...diffs)
  worst = Math.max(worst, maxDiff)

  // 1e-3 in real clinical units: float32 accumulation order differs between
  // torch's BLAS and a scalar JS loop, so bit-exactness is not achievable.
  const ok = maxDiff < 1e-3
  if (!ok) failures++
  console.log(
    `case ${i}  max abs diff ${maxDiff.toExponential(2)}  ${ok ? 'OK' : 'FAIL'}`,
  )
  if (!ok) {
    const j = diffs.indexOf(maxDiff)
    console.log(`   ${manifest.features[j].label}: ts ${actual[j]} vs torch ${testCase.expected[j]}`)
  }
})

console.log(`\nworst deviation across ${cases.length} cases: ${worst.toExponential(3)}`)
console.log(failures === 0 ? 'PARITY OK' : `PARITY FAILED (${failures} cases)`)
process.exit(failures === 0 ? 0 : 1)
